### ISSUE TITLE
installation failed using pip in main cmd shell

### ISSUE THREAD

**Issue by MPagel** [chrippa/backports.shutil_get_terminal_size#11]
> pip install backports-shutil_get_terminal_size
> Collecting backports-shutil_get_terminal_size
>   Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
> Installing collected packages: backports-shutil-get-terminal-size
> Exception:
> Traceback (most recent call last):
>   File "d:\programs\python\python27\lib\site-packages\pip\basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "d:\programs\python\python27\lib\site-packages\pip\commands\install.py", line 317, in run
>     prefix=options.prefix_path,
>   File "d:\programs\python\python27\lib\site-packages\pip\req\req_set.py", line 742, in install
>     **kwargs
>   File "d:\programs\python\python27\lib\site-packages\pip\req\req_install.py", line 831, in install
>     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
>   File "d:\programs\python\python27\lib\site-packages\pip\req\req_install.py", line 1032, in move_wheel_files
>     isolated=self.isolated,
>   File "d:\programs\python\python27\lib\site-packages\pip\wheel.py", line 348, in move_wheel_files
>     assert info_dir, "%s .dist-info directory not found" % req
> AssertionError: backports-shutil_get_terminal_size .dist-info directory not found

**Comment by MPagel** [comment]
(windows 8.1 x64)

**Comment by MPagel** [comment]
downloading package from this github repo and running python setup.py install appears to work. 

I think pip's problem is that it was looking for a .dist-info directory within the backports.shutil-get-terminal-size-1.0.0 parent directory, but instead it had created a  backports.shutil-get-terminal-size-1.0.0.dist-info directory and dumped the files in there.  I could not seem to execute a work-around by splitting the directory apart (with .dist.info being  sub of the other) and putting the full set of files (6?) into both backports.shutil... and .dist-info directories and re-running pip. So, this package's build in pip is borked, but it can be installed manually from this github repo.  Thanks

**Comment by MPagel** [comment]
pip 9.0.1 (2016-11-06) solves this issue.  It's possible pip 9.0.0 (2016-11-02) also did.
