### ISSUE TITLE
ImportError: No module named shutil_get_terminal_size

### ISSUE THREAD

**Issue by jacebrowning** [chrippa/backports.shutil_get_terminal_size#9]
The example in the README doesn't work for me:

```
$ pip install backports.shutil_get_terminal_size
Collecting backports.shutil_get_terminal_size
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Installing collected packages: backports.shutil-get-terminal-size
Successfully installed backports.shutil-get-terminal-size-1.0.0

$ python
Python 2.7.11 (default, May 13 2016, 22:46:09)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from backports.shutil_get_terminal_size import get_terminal_size
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named shutil_get_terminal_size
```

**Comment by jacebrowning** [comment]
But installation via:

`$ pip install https://github.com/chrippa/backports.shutil_get_terminal_size/archive/159e269450dbf37c3a837f6ea7e628d59acbb96a.zip`

**does** work. So maybe we just need a new release as requested in #7?

**Comment by mjdellwo** [comment]
Hello,
I'm having the same problem and there are many pages on the web devoted to this but not a lot of good insight.  Eg, https://github.com/ipython/ipython/issues/9656.  I too am coming to this by way of installing the latest IPython.

What I see is that when I look at https://pypi.python.org/pypi/backports.shutil_get_terminal_size/1.0.0, there is both a whl and a tar.gz that can be downloaded.  The .whl file includes a  backports subdirectory and a shutil_backports subdirectory.  The .tar.gz file is missing the shutil_backports directory.  Its backports directory is identical to the one from the wheel.  I suspect that this is the crux of the matter.

I am running on a fresh python 2.7.13, with latest pip and setuptools.  When I run pip and it uses the whl file, it works fine:
$ pip install --no-cache-dir --prefix=/tmp/test2 backports.shutil_get_terminal_size
Collecting backports.shutil_get_terminal_size
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Installing collected packages: backports.shutil-get-terminal-size
Successfully installed backports.shutil-get-terminal-size-1.0.0
$ env PYTHONPATH=/tmp/test2/lib/python2.7/site-packages python
Python 2.7.13 (default, Feb  8 2017, 22:55:47)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from backports.shutil_get_terminal_size import get_terminal_size
>>> get_terminal_size()
terminal_size(columns=155, lines=45)

When I try to install with --no-binary :all: flag, it installs OK but the import fails:

$ pip install --no-cache-dir --no-binary :all: --prefix=/tmp/test1 backports.shutil_get_terminal_size
Collecting backports.shutil_get_terminal_size
  Downloading backports.shutil_get_terminal_size-1.0.0.tar.gz
Installing collected packages: backports.shutil-get-terminal-size
  Running setup.py install for backports.shutil-get-terminal-size ... done
Successfully installed backports.shutil-get-terminal-size-1.0.0
$ env PYTHONPATH=/tmp/test1/lib/python2.7/site-packages /apps/pkgs/foss/base/python2.7/bin/python
Python 2.7.13 (default, Feb  8 2017, 22:55:47)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from backports.shutil_get_terminal_size import get_terminal_size
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named shutil_get_terminal_size

It so happens that in my typical installation case it will almost certainly always go to the .tar.gz file, this is due to my own constructs around maintaining a number package libraries under different prefixes.  I suspect many people have the same sort of issue.

I tried making a copy of the shutils_backports directory from the 'whl' install into this non-binary install.  I can then import shutil_backports itself, but I get the same error importing backports.shutil_get_terminal_size import get_terminal_size.

I compared the two 'backports' directories again post-install and they are still identical except for the binary *.pyc files that get created.
